name: macOS
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  pull_request:
    branches:
    - '**'

jobs:
  Build_Test-macOS-macOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_26.1.app/Contents/Developer'
    
    - name: Swift Version
      run: swift --version
    
    - name: Build using Swift x86_64
      run: swift build --triple x86_64-apple-macos
    - name: Build using Swift arm64
      run: swift build --triple arm64-apple-macos
    - name: Test using Swift
      run: swift test
    
    - name: Build using Xcode
      run: xcodebuild -scheme GateEngine ONLY_ACTIVE_ARCH=NO -destination platform=macOS -configuration Release
    - name: Test using Xcode
      run: xcodebuild -scheme GateEngine -destination platform=macOS test
